### ISSUE TITLE
Idea: Use a newt to find the dark cave

### ISSUE THREAD

**Issue by skylerberg** [SageBerg/St.GeorgeGame#15]
The idea is that you set your newt down and follow it and it leads you to the cave.

Option: "Set your newt free and see where it goes" or something like this.
Outcome ideas:
  "You follow the newt into a dark cave."
  "You spend hours following your newt around in circles."
  "After several hours you are no longer able to keep pace with the newt and lose track of it."
  "The newt was happier with you and doesn't want to leave."

**Comment by SageBerg** [comment]
I put this in the game.
