### ISSUE TITLE
Idea: Storm hits the pirate ship

### ISSUE THREAD

**Issue by skylerberg** [SageBerg/St.GeorgeGame#16]
If a storm hits the pirate ship you should have options to do things like 
"Panic!"
"Throw yourself overboard." 
"Pray to a higher power."
"Ask Lord Arthur what to do."
"Raise the sails."
"Hide beneath the deck." 
"Run around in circles."

**Comment by SageBerg** [comment]
"Throw yourself overboard." 

This made me laugh so hard my face turned all red.

**Comment by SageBerg** [comment]
done
