### ISSUE TITLE
Partial game update

### ISSUE THREAD

**Issue by skylerberg** [SageBerg/St.GeorgeGame#2]
I started the game by leaving in a huff, then I went to the market. I still have the option to go to the market even though I am there. I also only have a score of 1 even though I have taken two turns.

I also have the option to look for a weapon.

**Comment by skylerberg** [comment]
The game seems to be a bit sluggish. I have taken several more turns and my score has not been increasing all the times that it should.

**Comment by skylerberg** [comment]
Looking at the console I see `ReferenceError: functions is not defined`. This error happened three times on line 230 of `client.js` and once on line 287.

**Comment by SageBerg** [comment]
I fixed these things this morning. I just hadn't pushed them to the server yet.
